name: Run Tests

on:
  pull_request:
    branches:
      - develop 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x 

    - name: Change working directory to src
      run: cd src

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --verbosity normal
