name: Run Tests

on:
  pull_request:
    branches:
      - develop 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x 

    - name: Restore dependencies
      run: dotnet restore src/TrainTicketMachine.sln  # Zmodyfikuj ścieżkę do solucji

    - name: Run tests
      run: dotnet test src/TrainTicketMachine.sln --verbosity normal
